version: '3.1'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: picloud
      MYSQL_DATABASE: picloud
    volumes:
      - ./data:/var/lib/mysql
    ports:
     - "3307:3306"
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./webadmin/:/code
      - ./etc/:/etc/picloud
    ports:
      - 8000:8000

    depends_on:
      - db
